version: '3'
services:
  tomcat:
    container_name: tomcat
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./target/web-app.war:/usr/local/tomcat/webapps/web-app.war
    ports:
      - "8080:8080"
    networks:
      - java-network

networks:
  java-network:
    external: true